### ISSUE TITLE
[question] How to run a script?

### ISSUE THREAD

**Issue by fukamachi** [snmsts/roswell#13]
I thought `ros` also takes a file name of CL script to run, but it seems the script have to be formatted in some ways, like, it must have a function named `main`.

For example, this script cannot be run with `ros -Q script.lisp`.

```common-lisp
;; some comments. blah blah

(ql:quickload '(:cl-ppcre :cl+ssl :drakma :cl-json :simple-date-time))

(exit)
```

Can you clarify the format which a 'ros' script have to be?
And is there any ways to run a normal CL script with `ros` command?

**Comment by snmsts** [comment]
https://github.com/snmsts/roswell/blob/master/samples/hello.ros is only available example of `ros` script.
If you'd like to run ordinal lisp file for scripting.you'd better use `-l` option like `ros -Q -l script.lisp -q`

**Comment by snmsts** [comment]
I'll add `init` subcommand for the purpose make it ease blank script.
I just to much forcus on windows porting so forget about the plan sorry.

**Comment by fukamachi** [comment]
Thanks.
It would be great if you'll add it to README ;)
