### ISSUE TITLE
[question] Is there a way to change which Quicklisp to load with `-Q`?

### ISSUE THREAD

**Issue by fukamachi** [snmsts/roswell#24]
I wrote 2 Roswell scripts today. One for [qlot](https://github.com/fukamachi/qlot) and another for [clack](https://github.com/fukamachi/clack).

- https://github.com/fukamachi/qlot/blob/master/bin/qlot.ros
- https://github.com/fukamachi/clack/blob/master/bin/clackup.ros

`clackup.ros` is a command-line interface for `clack:clackup` will be used like this.

```
# equivalent to (clack:clackup #P"app.lisp" :server :woo :port 8080)
$ clackup.ros app.lisp --server woo --port 8080
```

`qlot.ros` is another individual script for qlot.

```
$ qlot.ros install
$ qlot.ros update
```

I'm thinking of adding another subcommand `exec` to it which will be used like this.

```
$ qlot.ros exec -- clackup.ros app.lisp --server woo --port 8080
$ qlot.ros exec myapp -- clackup.ros app.lisp --server woo --port 8080
```

`exec` takes a shell command to execute with a project-local Quicklisp.
For writing a script like it, I think I have to change the `*quicklisp-home*` will be loaded by `-Q` option.

So, is there a way like it?
Or, other ideas would be appreciated.

**Comment by snmsts** [comment]
There is no straight way to do that for now. 

If I fix the line
https://github.com/snmsts/roswell/blob/master/src/cmds/run/cmd.c#L142
not to overwirte option.

then you can write like below
`ros quicklisp=/path/to/setup.lisp -Q blabla`

**Comment by fukamachi** [comment]
It doesn't work in my case because `clack.ros` and `qlot.ros` are individual commands and `qlot.ros` cannot overwrite the `ros` argument for `clack.ros`.
I think using an environment like `QUICKLISP_HOME` would be nice in this case, though I know you don't like an environment variable.

**Comment by snmsts** [comment]
Thank you verymuch for your explanation, I think now I understand your situation.
I felt for your case I'd like to change `ros:quicklisp` function to take optional parameter to specify freely which path to load quicklisp and you can use roswell script with `+Q` option with calling the function from the script.

I don't want too much on `Q` option by roswell if user want control quicklisp,the user should use `+Q` and take responsibility on it.

**Comment by fukamachi** [comment]
Well, let me get it straight.
Can I write a Roswell script which takes any shell commands with a specific Quicklisp home?

`qlot.ros exec` is like a such command.
If it takes a command of another Roswell script, it changes the default Quicklisp even if it invokes `ros` with `-Q` option.

I don't wanna modify `clack.ros` to make it work with `qlot.ros` because those commands are separated and shouldn't depend on each other.

**Comment by snmsts** [comment]
May be it is still not satisfactory with you, but I'd like to show an example.
https://gist.github.com/snmsts/5aeba076e9729f92b404
If you write `+Q `in script,it will win `-Q` specified on command line.
from my opinion `-Q` and `-L` should be fatal for some kind of script file.
So I'd like to fix it if script writer specified it.

**Comment by snmsts** [comment]
I wrote the feature.

https://github.com/snmsts/roswell/commit/8568debf6d93056517f563e28fbaccddec1aee8c

**Comment by fukamachi** [comment]
Thanks!
