### ISSUE TITLE
Ugly download logs

### ISSUE THREAD

**Issue by fukamachi** [snmsts/roswell#34]
It doesn't output a line break at the last of progress dots when the download has finished.

![screen shot 2015-06-06 at 10 47 38 am](https://cloud.githubusercontent.com/assets/90570/8017746/9ed2919e-0c39-11e5-9b15-9e0e09ca964a.png)

**Comment by snmsts** [comment]
https://travis-ci.org/snmsts/roswell/jobs/65657568

I hope it's fixed.

**Comment by fukamachi** [comment]
Looks better. Thanks!
