### ISSUE TITLE
'exec' doesn't seem to work with ccl-bin

### ISSUE THREAD

**Issue by fukamachi** [snmsts/roswell#43]
It seems `ros exec` doesn't work with Clozure CL because `ccl::%execvp` expects `MACPTR` for its argument.

Here's the error logs when I execute `qlot install` on Travis CI:

https://travis-ci.org/fukamachi/lack/jobs/66845685#L314-L319

```
> Error: The value ("ros" "-Q" "-s" "qlot" "-e" "(qlot:install)") is not of the expected type MACPTR.
> While executing: CCL::%EXECVP, in process listener(1).
> Type :GO to continue, :POP to abort, :R for a list of available restarts.
> If continued: Skip evaluation of (ros:run '((:script "/home/travis/.roswell/bin/qlot""install")(:quit ())))
> Type :? for other options.
1 > 
```

**Comment by snmsts** [comment]
I gave up.
880601062bc101e6162b7ddcbe2baed8b14d0d35
sorry for inconvenience

**Comment by fukamachi** [comment]
It looks fine for now.
You don't have to feel sorry about this kind of stuff. I'm very thankful to your hard works on Roswell.

**Comment by snmsts** [comment]
Thanks. It's my pleasure. :)
