### ISSUE TITLE
reimplement in Go

### ISSUE THREAD

**Issue by snmsts** [snmsts/roswell#49]
It is said that C is too sensitive to commit.

**Comment by luismbo** [comment]
How about... Lisp? :-)

**Comment by snmsts** [comment]
Are there any good implementation?

**Comment by luismbo** [comment]
What are your requirements?

**Comment by snmsts** [comment]
Of course I want to use common lisp.
1. stability is the most important I don't want to debug the implementation for this project.
2.portability is important as well.same source code could be used for produce executable for different CPUs at least Intel and Arm.
3.It should be well maintained on os Windows Linux osx.
4.the size of executables should be small enough for small memory environment.
I think among common lisps SBCL,ECL,MKCL could be candidates but SBCL is just too big.
ECL/MKCL are not reliable enough for the purpose.

**Comment by luismbo** [comment]
What issues did you have with ECL? (I'm sure the current maintainer would love to hear about them. :-))

**Comment by snmsts** [comment]
hmm...I haven't try ECL more than 5 years,So I don't know well about current state.
My impression for ECL was
It's Ok for unix.It's not easy to use windows(integrate with compiler is hard).runtime is not small enough.
Am I wrong?

**Comment by snmsts** [comment]
https://github.com/snmsts/roswell/issues/9 I'll investigate ecl first...

**Comment by Rudolph-Miller** [comment]
Don't you use https://github.com/codegangsta/cli?

**Comment by snmsts** [comment]
I don't have any plan to use library. It's my initiation period of the language as well :)

**Comment by Rudolph-Miller** [comment]
Okay. :)

**Comment by snmsts** [comment]
not motivated for now. :( someday.
