### ISSUE TITLE
Implicit 'ros build' is problematic

### ISSUE THREAD

**Issue by fukamachi** [snmsts/roswell#53]
Roswell makes an executable from a ros script when `ros install [library]` since 0.0.3.38. However, it's not transparent and has some issues.

* The executable includes Quicklisp the 'ros install' was running with.

It would be a problem if the script interacts with Quicklisp, like loading other libraries dynamically. It also made Qlot's `qlot` command totally useless because it cannot switch Quicklisp path to use anymore.

* SBCL_HOME has to be set for executables

It seems SBCL_HOME has to be set in executables unless it doesn't need to load SBCL contribs.

I think the implicit building is great only if we don't have to care about those differences. We need to solve the above problems, or give up the implicit building.

**Comment by snmsts** [comment]
Sure. I think there is no easy solution for these issues.
I decide to revert the change for now.
It is better to think more on how to switch which script shoud be dumped execute or read every time.

**Comment by fukamachi** [comment]
That sounds a good decision to me.

**Comment by snmsts** [comment]
done.

**Comment by fukamachi** [comment]
Thanks!
