### ISSUE TITLE
error in install sbcl

### ISSUE THREAD

**Issue by cxxxr** [snmsts/roswell#65]
$ ros install sbcl
    Checking version to install....
    Downloading https://github.com/sbcl/sbcl/releases
      46K downloaded.
    Downloading http://beta.quicklisp.org/archive/cl-html-parse/2014-01-13/cl-html-parse-20140113-git.tgz
    ##########################################################################  99%
    Using 'sbcl-bin' to compile SBCL. (default)
    Downloading archive: https://github.com/sbcl/sbcl/archive/sbcl-1.2.14.tar.gz
    Downloading https://github.com/sbcl/sbcl/archive/sbcl-1.2.14.tar.gz
       6M downloaded.
    
    Extracting archive:/home/fr/.roswell/archives/sbcl-1.2.14.tar.gz
         0 ......................................................................
       700 ......................................................................
      1400 ......................................................................
      2100 ......................................................................
      2800 ......................................................................
      3500 ......................................................................
      4200 ......................................................................
      4900 ......................................................................
      5600 ......................................................................
      6300 ......................................................................
      7000 ......................................................................
      7700 ......................................................................
      8400 ......................................................................
      9100 ......................................................................
      9800 ......................................................................
     10500 ................................
    Installing sbcl/1.2.14
    prefix: #P"/home/fr/.roswell/impls/x86-64/linux/sbcl/1.2.14/"
    chdir /home/fr/.roswell/src/sbcl-1.2.14/
         0 .Unhandled UIOP/RUN-PROGRAM:SUBPROCESS-ERROR in thread #<SB-THREAD:THREAD
                                                            "main thread" RUNNING
                                                             {1002BF7763}>:
      Subprocess (:PROCESS
                  #<SB-IMPL::PROCESS
                    :EXITED 1>) run with command "/bin/bash install.sh" exited with error code 1
    
    Backtrace for: #<SB-THREAD:THREAD "main thread" RUNNING {1002BF7763}>
    0: ((LAMBDA NIL :IN SB-DEBUG::FUNCALL-WITH-DEBUG-IO-SYNTAX))
    1: (SB-IMPL::CALL-WITH-SANE-IO-SYNTAX #<CLOSURE (LAMBDA NIL :IN SB-DEBUG::FUNCALL-WITH-DEBUG-IO-SYNTAX) {1004691B9B}>)
    2: (SB-IMPL::%WITH-STANDARD-IO-SYNTAX #<CLOSURE (LAMBDA NIL :IN SB-DEBUG::FUNCALL-WITH-DEBUG-IO-SYNTAX) {1004691B6B}>)
    3: (SB-DEBUG:PRINT-BACKTRACE :STREAM #<SYNONYM-STREAM :SYMBOL SB-SYS:*STDERR* {10001527C3}> :START 0 :FROM :INTERRUPTED-FRAME :COUNT NIL :PRINT-THREAD T :PRINT-FRAME-SOURCE NIL :METHOD-FRAME-STYLE NIL)
    4: (SB-DEBUG::DEBUGGER-DISABLED-HOOK #<UIOP/RUN-PROGRAM:SUBPROCESS-ERROR {100468D1B3}> #<unavailable argument>)
    5: (SB-DEBUG::RUN-HOOK SB-EXT:*INVOKE-DEBUGGER-HOOK* #<UIOP/RUN-PROGRAM:SUBPROCESS-ERROR {100468D1B3}>)
    6: (INVOKE-DEBUGGER #<UIOP/RUN-PROGRAM:SUBPROCESS-ERROR {100468D1B3}>)
    7: (CERROR "IGNORE-ERROR-STATUS" UIOP/RUN-PROGRAM:SUBPROCESS-ERROR :COMMAND "/bin/bash install.sh" :CODE 1 :PROCESS (:PROCESS #<SB-IMPL::PROCESS :EXITED 1>))
    8: (UIOP/RUN-PROGRAM::%CHECK-RESULT 1 :COMMAND "/bin/bash install.sh" :PROCESS (:PROCESS #<SB-IMPL::PROCESS :EXITED 1>) :IGNORE-ERROR-STATUS NIL)
    9: ((FLET #:CLEANUP-FUN-7332 :IN UIOP/RUN-PROGRAM::%USE-RUN-PROGRAM)) [cleanup]
    10: ((LAMBDA (UIOP/RUN-PROGRAM::REDUCED-INPUT UIOP/RUN-PROGRAM::INPUT-ACTIVITY) :IN UIOP/RUN-PROGRAM::%USE-RUN-PROGRAM) NIL NIL)
    11: (UIOP/RUN-PROGRAM::%USE-RUN-PROGRAM "/bin/bash install.sh" :INPUT NIL :ERROR-OUTPUT NIL :IF-INPUT-DOES-NOT-EXIST :ERROR :IF-OUTPUT-EXISTS :OVERWRITE :IF-ERROR-OUTPUT-EXISTS :OVERWRITE :ELEMENT-TYPE :DEFAULT :EXTERNAL-FORMAT :UTF-8 :OUTPUT T)
    12: (SBCL-INSTALL (:TARGET "sbcl" :VERSION "1.2.14" :ARGV NIL))
    13: (MAIN "install" "sbcl")
    14: (SB-INT:SIMPLE-EVAL-IN-LEXENV (APPLY (QUOTE MAIN) ROS:*ARGV*) #<NULL-LEXENV>)
    15: (SB-EXT:EVAL-TLF (APPLY (QUOTE MAIN) ROS:*ARGV*) NIL #<NULL-LEXENV>)
    16: ((LABELS SB-FASL::EVAL-FORM :IN SB-INT:LOAD-AS-SOURCE) (APPLY (QUOTE MAIN) ROS:*ARGV*) NIL)
    17: (SB-INT:LOAD-AS-SOURCE #<CONCATENATED-STREAM :STREAMS NIL {1005E867D3}> :VERBOSE NIL :PRINT NIL :CONTEXT "loading")
    18: ((FLET SB-FASL::LOAD-STREAM :IN LOAD) #<CONCATENATED-STREAM :STREAMS NIL {1005E867D3}> NIL)
    19: (LOAD #<CONCATENATED-STREAM :STREAMS NIL {1005E867D3}> :VERBOSE NIL :PRINT NIL :IF-DOES-NOT-EXIST T :EXTERNAL-FORMAT :DEFAULT)
    20: (ROS:SCRIPT :SCRIPT "/usr/local/share/common-lisp/source/roswell/install.lisp" "install" "sbcl" "()" "((\"sbcl-bin.version\"\"1.2.14\")(\"default.lisp\"\"sbcl-bin\"))" "/home/fr/.roswell/" "ros")
    21: (ROS:RUN ((:SCRIPT "/usr/local/share/common-lisp/source/roswell/install.lisp" "install" "sbcl" "()" "((\"sbcl-bin.version\"\"1.2.14\")(\"default.lisp\"\"sbcl-bin\"))" "/home/fr/.roswell/" "ros") (:QUIT NIL)))
    22: (SB-INT:SIMPLE-EVAL-IN-LEXENV (ROS:RUN (QUOTE ((:SCRIPT "/usr/local/share/common-lisp/source/roswell/install.lisp" "install" "sbcl" "()" "((\"sbcl-bin.version\"\"1.2.14\")(\"default.lisp\"\"sbcl-bin\"))" "/home/fr/.roswell/" "ros") (:QUIT NIL)))) #<NULL-LEXENV>)
    23: (EVAL (ROS:RUN (QUOTE ((:SCRIPT "/usr/local/share/common-lisp/source/roswell/install.lisp" "install" "sbcl" "()" "((\"sbcl-bin.version\"\"1.2.14\")(\"default.lisp\"\"sbcl-bin\"))" "/home/fr/.roswell/" "ros") (:QUIT NIL)))))
    24: (SB-IMPL::PROCESS-EVAL/LOAD-OPTIONS ((:EVAL . "(progn #-ros.init(cl:load \"/usr/local/share/common-lisp/source/roswell/init.lisp\"))") (:EVAL . "(ros:quicklisp)") (:EVAL . "(ros:run '((:script \"/usr/local/share/common-lisp/source/roswell/install.lisp\"\"install\"\"sbcl\"\"()\"\"((\\\"sbcl-bin.version\\\"\\\"1.2.14\\\")(\\\"default.lisp\\\"\\\"sbcl-bin\\\"))\"\"/home/fr/.roswell/\"\"ros\")(:quit ())))")))
    25: (SB-IMPL::TOPLEVEL-INIT)
    26: ((FLET #:WITHOUT-INTERRUPTS-BODY-83 :IN SB-EXT:SAVE-LISP-AND-DIE))
    27: ((LABELS SB-IMPL::RESTART-LISP :IN SB-EXT:SAVE-LISP-AND-DIE))
    
    unhandled condition in --disable-debugger mode, quitting

**Comment by snmsts** [comment]
I don't know exact reason.
But I guess libraries needed for compiling sbcl are missing.
For example you install zlib-devel?

**Comment by cxxxr** [comment]
it's exactly that
thank you.

**Comment by snmsts** [comment]
Thank you.

**Comment by luoxing91** [comment]
I have the same problem , but I have 'yum install zlib-devel'

**Comment by alecStewart1** [comment]
This is also still an issue for me.

**Comment by wmealing** [comment]
Getting the same.

**Comment by wmealing** [comment]
2.2.8 is fine 2.2.9 is not working.
