### ISSUE TITLE
Roswell on armv7, Gentoo

### ISSUE THREAD

**Issue by pimiento** [snmsts/roswell#75]
It was compiled and installed, I have installed SBCL:

    [I] dev-lisp/sbcl (1.2.15@09/27/2015)

And I can run sbcl repl on that machine. But when I'm trying to install clack with Roswell:

    $> ros install clack

I got the error message:

    Installing sbcl-bin...
    ########################################################################## 100%
    this architecture is not supported.stop
    Segmentation fault

**Comment by snmsts** [comment]
armv7
Thank you for your report.
I'd like to support it,but I'm not knowledgeable about it. please help me.

First, I'd like to know result of commands below.
% uname
% uname -m
% ros roswell-internal-use uname
% ros roswell-internal-use uname -m

Second,which sbcl is appropriate? 
I guess ARMel or ARMhf on the table below.
http://www.sbcl.org/platform-table.html

**Comment by pimiento** [comment]
senior-pimiento roswell # uname
    Linux
    senior-pimiento roswell # uname -a
    Linux senior-pimiento 3.2.34-30 #17 SMP Mon Apr 13 15:53:45 UTC 2015 armv7l Online Labs C1 GNU/Linux
    senior-pimiento roswell # ros roswell-internal-use uname
    linux
    senior-pimiento roswell # ros roswell-internal-use uname -m
    armv7l

It was built on:

    gcc (Gentoo 4.9.3 p1.2, pie-0.6.3) 4.9.3

**Comment by snmsts** [comment]
Thank you @pimiento  for the first question.
For the second question,I'd like to add farther information that I'd like to know.
According to the http://www.sbcl.org/platform-table.html ,there are two type of arm official distribution by sbcl.org.
http://prdownloads.sourceforge.net/sbcl/sbcl-1.2.7-armel-linux-binary.tar.bz2
http://prdownloads.sourceforge.net/sbcl/sbcl-1.2.14-armhf-linux-binary.tar.bz2

I'd like to which is appropriate for your CPU type.
The failure you did see was caused current roswell can't associate 'armv7l' with 'armel' nor 'armhf'.
So what I'm asking you is try download each of archive and extract it and try ./run-sbcl.sh in the extracted directory.I'm not sure how I should decide when both works but if one of which are not working It is helpful to avid associating with that.

Thank you in advance.

**Comment by pimiento** [comment]
Ok.

1. sbcl-1.2.14-armhf-linux-binary.tar.bz2 works ok
2. sbcl-1.2.7-armel-linux-binary.tar.bz2

        senior-pimiento sbcl-1.2.7-armel-linux # ./run-sbcl.sh 
        (running SBCL from: .)
        ./run-sbcl.sh: line 58: /root/sbcl-1.2.7-armel-linux/src/runtime/sbcl: No such file or directory

  while:

      senior-pimiento sbcl-1.2.7-armel-linux # file /root/sbcl-1.2.7-armel-linux/src/runtime/sbcl 
      /root/sbcl-1.2.7-armel-linux/src/runtime/sbcl: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux.so.3, for GNU/Linux 2.6.32, BuildID[sha1]=8c5fac99825088a8d46aa5bc3bd9603ca5e700bf, not stripped

**Comment by snmsts** [comment]
I checked source... and found typo.
https://github.com/snmsts/roswell/commit/2f1f5d3f9dd4adb26d7ea1fe9ef4e15697aa04db
I might support it once but might break it...

It might work on master branch now.
% readelf -A /proc/self/exe |grep Tag_ABI_VFP_args|wc -l
hope the result of it is not '0' for you.

**Comment by pimiento** [comment]
Ok. Now it's working well with

    ros -Q -e '(ql:quickload :quicklisp-slime-helper)' -q

Only it do nothing when I type

    ros install clack

I don't know, is it something with armv7.

**Comment by snmsts** [comment]
how about 

    ros -Q -e '(ql:quickload :clack)' -q

?
if it success then I don't know what's wrong.

I do nothing special for armv7

    ros install clack

it may just to slow.

**Comment by pimiento** [comment]
No, it doesn't work anyway. It seems like another problem. That one bug with armv7l is fixed.

**Comment by pimiento** [comment]
Ok, some problems are still here. Here is info about my system sbcl:

    pimiento@senior-pimiento ~ $ file /usr/bin/sbcl
    /usr/bin/sbcl: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-armhf.so.3, for GNU/Linux 2.6.32, stripped

And here is about roswell's version:

    pimiento@senior-pimiento ~ $ file /home/pimiento/.roswell/impls/armel/linux/sbcl-bin/1.2.7/bin/sbcl 
    /home/pimiento/.roswell/impls/armel/linux/sbcl-bin/1.2.7/bin/sbcl: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux.so.3, for GNU/Linux 2.6.32, BuildID[sha1]=8c5fac99825088a8d46aa5bc3bd9603ca5e700bf, not stripped

I've added link for /lib/ld-linux.so.3 so now it looks like:

    pimiento@senior-pimiento ~ $ ls -l /lib/ld-*
    -rwxr-xr-x 1 root root 134192 Sep 27 02:26 /lib/ld-2.21.so
    lrwxrwxrwx 1 root root     10 Sep 27 02:27 /lib/ld-linux-armhf.so.3 -> ld-2.21.so
    lrwxrwxrwx 1 root root     15 Oct 26 11:40 /lib/ld-linux.so.3 -> /lib/ld-2.21.so

System sbcl works well, but when I'm trying to run roswell's version, I've got that message:

    pimiento@senior-pimiento ~ $ .roswell/impls/armel/linux/sbcl-bin/1.2.7/bin/sbcl 
    This is SBCL 1.2.7, an implementation of ANSI Common Lisp.
    More information about SBCL is available at <http://www.sbcl.org/>.
    
    SBCL is free software, provided as is, with absolutely no warranty.
    It is mostly in the public domain; some portions are provided under
    BSD-style licenses.  See the CREDITS and COPYING files in the
    distribution for more information.
    fatal error encountered in SBCL pid 5619:
    can't load .core for different runtime, sorry
    
    Welcome to LDB, a low-level debugger for the Lisp runtime environment.
    ldb> 

Any ideas how to make roswell works well?

**Comment by snmsts** [comment]
specify core is required to run sbcl correctly.
This is how to run sbcl installed by roswell by yourhand.

```
~ $ .roswell/impls/x86-64/darwin/sbcl-bin/1.2.11/bin/sbcl
fatal error encountered in SBCL pid 8933:
can't find core file at /usr/local/lib/sbcl//sbcl.core


~ $ .roswell/impls/x86-64/darwin/sbcl-bin/1.2.11/bin/sbcl --core .roswell/impls/x86-64/darwin/sbcl-bin/1.2.11/lib/sbcl/sbcl.core
This is SBCL 1.2.11, an implementation of ANSI Common Lisp.
More information about SBCL is available at <http://www.sbcl.org/>.

SBCL is free software, provided as is, with absolutely no warranty.
It is mostly in the public domain; some portions are provided under
BSD-style licenses.  See the CREDITS and COPYING files in the
distribution for more information.
* (quit)
```

BTW I'd like to test arm platform. What are you using? Do you have recommendation for this purpose?

Raspberry PI2?

**Comment by pimiento** [comment]
I'm using dedicated arm server on https://www.scaleway.com/

**Comment by pimiento** [comment]
I think, the problem is that my system sbcl version is 1.2.15 and roswell's sbcl tries to run some libraries was built with system sbcl.

```
Checking version to install....
Downloading https://github.com/sbcl/sbcl/releases.atom
  20K downloaded.
Using 'sbcl-bin' to compile SBCL. (default)
Downloading archive: https://github.com/sbcl/sbcl/archive/sbcl-1.2.16.tar.gz
Downloading https://github.com/sbcl/sbcl/archive/sbcl-1.2.16.tar.gz
   6M downloaded.d.

Extracting archive:/home/pimiento/.roswell/archives/sbcl-1.2.16.tar.gz
     0 ......Unhandled UIOP/RUN-PROGRAM:SUBPROCESS-ERROR:
  Subprocess (:PROCESS
              #<SB-IMPL::PROCESS :EXITED 1>) run with command ("/bin/bash"
                                                               "-lc"
                                                               "cd \"/home/pimiento/.roswell/src/sbcl-1.2.16/\";/bin/bash ./make.sh '--xc-host=ros lisp=sbcl-bin --no-rc run -- --disable-debugger' '--prefix=/home/pimiento/.roswell/impls/armhf/linux/sbcl/1.2.16/'") exited with error code 1

Backtrace for: #<SB-THREAD:THREAD "main thread" RUNNING {52F448B1}>
0: ((LAMBDA NIL :IN SB-DEBUG::FUNCALL-WITH-DEBUG-IO-SYNTAX))
1: (SB-IMPL::CALL-WITH-SANE-IO-SYNTAX #<CLOSURE (LAMBDA NIL :IN SB-DEBUG::FUNCALL-WITH-DEBUG-IO-SYNTAX) {51C3DABD}>)
2: (SB-IMPL::%WITH-STANDARD-IO-SYNTAX #<CLOSURE (LAMBDA NIL :IN SB-DEBUG::FUNCALL-WITH-DEBUG-IO-SYNTAX) {51C3DAA5}>)
3: (SB-DEBUG:PRINT-BACKTRACE :STREAM #<SYNONYM-STREAM :SYMBOL SB-SYS:*STDERR* {4F04B541}> :START 0 :FROM :INTERRUPTED-FRAME :COUNT NIL :PRINT-THREAD T :PRINT-FRAME-SOURCE NIL :METHOD-FRAME-STYLE NIL)
4: (SB-DEBUG::DEBUGGER-DISABLED-HOOK #<UIOP/RUN-PROGRAM:SUBPROCESS-ERROR {51C3A7E9}> #<unavailable argument>)
5: (SB-DEBUG::RUN-HOOK SB-EXT:*INVOKE-DEBUGGER-HOOK* #<UIOP/RUN-PROGRAM:SUBPROCESS-ERROR {51C3A7E9}>)
6: (INVOKE-DEBUGGER #<UIOP/RUN-PROGRAM:SUBPROCESS-ERROR {51C3A7E9}>)
7: (CERROR "IGNORE-ERROR-STATUS" UIOP/RUN-PROGRAM:SUBPROCESS-ERROR :COMMAND ("/bin/bash" "-lc" "cd \"/home/pimiento/.roswell/src/sbcl-1.2.16/\";/bin/bash ./make.sh '--xc-host=ros lisp=sbcl-bin --no-rc run -- --disable-debugger' '--prefix=/home/pimiento/.roswell/impls/armhf/linux/sbcl/1.2.16/'") :CODE 1 :PROCESS (:PROCESS #<SB-IMPL::PROCESS :EXITED 1>))
8: (UIOP/RUN-PROGRAM::%CHECK-RESULT 1 :COMMAND ("/bin/bash" "-lc" "cd \"/home/pimiento/.roswell/src/sbcl-1.2.16/\";/bin/bash ./make.sh '--xc-host=ros lisp=sbcl-bin --no-rc run -- --disable-debugger' '--prefix=/home/pimiento/.roswell/impls/armhf/linux/sbcl/1.2.16/'") :PROCESS (:PROCESS #<SB-IMPL::PROCESS :EXITED 1>) :IGNORE-ERROR-STATUS NIL)
9: ((FLET #:CLEANUP-FUN-6939 :IN UIOP/RUN-PROGRAM::%USE-RUN-PROGRAM)) [cleanup]
10: ((LAMBDA (UIOP/RUN-PROGRAM::REDUCED-INPUT UIOP/RUN-PROGRAM::INPUT-ACTIVITY) :IN UIOP/RUN-PROGRAM::%USE-RUN-PROGRAM) NIL NIL)
11: (UIOP/RUN-PROGRAM::%USE-RUN-PROGRAM ("/bin/bash" "-lc" "cd \"/home/pimiento/.roswell/src/sbcl-1.2.16/\";/bin/bash ./make.sh '--xc-host=ros lisp=sbcl-bin --no-rc run -- --disable-debugger' '--prefix=/home/pimiento/.roswell/impls/armhf/linux/sbcl/1.2.16/'") :INPUT NIL :ERROR-OUTPUT NIL :IF-INPUT-DOES-NOT-EXIST :ERROR :IF-OUTPUT-EXISTS :OVERWRITE :IF-ERROR-OUTPUT-EXISTS :OVERWRITE :ELEMENT-TYPE :DEFAULT :EXTERNAL-FORMAT :UTF-8 :OUTPUT T :IGNORE-ERROR-STATUS NIL)
12: (SBCL-MAKE (:TARGET "sbcl" :VERSION "1.2.16" :ARGV NIL))
13: (MAIN "install" "sbcl")
14: (SB-INT:SIMPLE-EVAL-IN-LEXENV (APPLY (QUOTE MAIN) ROS:*ARGV*) #<NULL-LEXENV>)
15: (SB-EXT:EVAL-TLF (APPLY (QUOTE MAIN) ROS:*ARGV*) NIL #<NULL-LEXENV>)
16: ((LABELS SB-FASL::EVAL-FORM :IN SB-INT:LOAD-AS-SOURCE) (APPLY (QUOTE MAIN) ROS:*ARGV*) NIL)
17: (SB-INT:LOAD-AS-SOURCE #<CONCATENATED-STREAM :STREAMS NIL {52DAD219}> :VERBOSE NIL :PRINT NIL :CONTEXT "loading")
18: ((FLET SB-FASL::LOAD-STREAM :IN LOAD) #<CONCATENATED-STREAM :STREAMS NIL {52DAD219}> NIL)
19: (LOAD #<CONCATENATED-STREAM :STREAMS NIL {52DAD219}> :VERBOSE NIL :PRINT NIL :IF-DOES-NOT-EXIST T :EXTERNAL-FORMAT :DEFAULT)
20: (ROS:SCRIPT :SCRIPT "/usr/local/share/common-lisp/source/roswell/install.lisp" "install" "sbcl" "()" "()" "0")
21: (ROS:RUN ((:SCRIPT "/usr/local/share/common-lisp/source/roswell/install.lisp" "install" "sbcl" "()" "()" "0") (:QUIT NIL)))
22: (SB-INT:SIMPLE-EVAL-IN-LEXENV (ROS:RUN (QUOTE ((:SCRIPT "/usr/local/share/common-lisp/source/roswell/install.lisp" "install" "sbcl" "()" "()" "0") (:QUIT NIL)))) #<NULL-LEXENV>)
23: (EVAL (ROS:RUN (QUOTE ((:SCRIPT "/usr/local/share/common-lisp/source/roswell/install.lisp" "install" "sbcl" "()" "()" "0") (:QUIT NIL)))))
24: (SB-IMPL::PROCESS-EVAL/LOAD-OPTIONS ((:EVAL . "(progn #-ros.init(cl:load \"/usr/local/share/common-lisp/source/roswell/init.lisp\"))") (:EVAL . "(ros:quicklisp)") (:EVAL . "(ros:run '((:script \"/usr/local/share/common-lisp/source/roswell/install.lisp\"\"install\"\"sbcl\"\"()\"\"()\"\"0\")(:quit ())))")))
25: (SB-IMPL::TOPLEVEL-INIT)
26: ((FLET #:WITHOUT-INTERRUPTS-BODY-69 :IN SB-EXT:SAVE-LISP-AND-DIE))
27: ((LABELS SB-IMPL::RESTART-LISP :IN SB-EXT:SAVE-LISP-AND-DIE))

unhandled condition in --disable-debugger mode, quitting
```

**Comment by snmsts** [comment]
fixed. https://github.com/snmsts/roswell/commit/2e3c890bfaf8444bcbede82fb5ea172285fbaac6
