### ISSUE TITLE
make failed on my mac

### ISSUE THREAD

**Issue by Habens** [snmsts/roswell#78]
>
➜  roswell git:(master) ✗ make
/Applications/Xcode.app/Contents/Developer/usr/bin/make  all-recursive
Making all in src
printf "#define ROS_COMPILE_ENVIRONMENT \"%s\"\n" "`gcc --version|head -n 1`" > gend.h.tmp
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
(printf "#define ROS_REVISION \"" && ((which git>/dev/null&&[ -e ../.git ]&& \
        (git log -n 1 --oneline|cut -d' ' -f1| tr -d '\n'| tr -d '\r'))||printf "") && printf "\"\n") >> gend.h.tmp
(sh -c 'cd /usr/local/share/common-lisp/source/roswell; pwd -W' 2>&1 >/dev/null && (printf "#define WIN_LISP_PATH \"" \
        echo `sh -c 'cd /usr/local/share/common-lisp/source/roswell; pwd -W 2>/dev/null'`| tr -d '\n'| tr -d '\r' |\
        sed /\//\\/ \
        printf "\\\\\"\n")  >> gend.h.tmp) || printf ""
sh: line 0: pwd: -W: invalid option
pwd: usage: pwd [-LP]
cmp -s gend.h.tmp gend.h||cp gend.h.tmp gend.h
rm -f gend.h.tmp
cat gend.h
#define ROS_COMPILE_ENVIRONMENT "Apple LLVM version 6.1.0 (clang-602.0.49) (based on LLVM 3.6.0svn)"
#define ROS_REVISION "b3293ce"

**Comment by snmsts** [comment]
I don't understand what did you do to build roswell. and why do you think your result is failure?
Why do you think so.Tell me more about failure please.

result of make on my environment is like below.

```
snmsts-air1-5644:roswell snmsts$ make
/Applications/Xcode.app/Contents/Developer/usr/bin/make  all-recursive
Making all in src
printf "#define ROS_COMPILE_ENVIRONMENT \"%s\"\n" "`gcc --version|head -n 1`" > gend.h.tmp
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/c++/4.2.1
(printf "#define ROS_REVISION \"" && ((which git>/dev/null&&[ -e ../.git ]&& \
	(git log -n 1 --oneline|cut -d' ' -f1| tr -d '\n'| tr -d '\r'))||printf "") && printf "\"\n") >> gend.h.tmp
(sh -c 'cd /usr/local/share/common-lisp/source/roswell; pwd -W' 2>&1 >/dev/null && (printf "#define WIN_LISP_PATH \"" \
	echo `sh -c 'cd /usr/local/share/common-lisp/source/roswell; pwd -W 2>/dev/null'`| tr -d '\n'| tr -d '\r' |\
	sed /\//\\/ \
	printf "\\\\\"\n")  >> gend.h.tmp) || printf ""
sh: line 0: pwd: -W: invalid option
pwd: usage: pwd [-LP]
cmp -s gend.h.tmp gend.h||cp gend.h.tmp gend.h
rm -f gend.h.tmp
cat gend.h
#define ROS_COMPILE_ENVIRONMENT "Apple LLVM version 7.0.0 (clang-700.0.72)"
#define ROS_REVISION "5316295"
```

looked scary?

```
snmsts-air1-5644:roswell snmsts$ echo $?
0
```

but it is expected result.I have ``src/ros`` properly.

**Comment by Habens** [comment]
Thanks for you quick reply!

I wanna install roswell and follow your [github wiki](https://github.com/snmsts/roswell/wiki). 
"brew install roswell" result:
>
ast 15 lines from /Users/wjchen/Library/Logs/Homebrew/roswell/03.make:
mv -f .deps/cmd-install.Tpo .deps/cmd-install.Po
mv -f .deps/cmd-help.Tpo .deps/cmd-help.Po
mv -f .deps/cmd-config.Tpo .deps/cmd-config.Po
mv -f .deps/cmd-setup.Tpo .deps/cmd-setup.Po
mv -f .deps/cmd-version.Tpo .deps/cmd-version.Po
clang  -g -O2   -o ros lsp.o opt.o download.o archive.o html.o util_list.o util.o util_string.o util_dir.o util_system.o cmd-internal.o cmd-version.o cmd-run.o cmd-run-sbcl.o cmd-run-ccl.o cmd-run-clisp.o cmd-run-ecl.o cmd-run-abcl.o cmd-run-cmu.o cmd-run-acl.o cmd-install.o cmd-install-sbcl-bin.o cmd-install-quicklisp.o cmd-help.o cmd-config.o cmd-setup.o  -lcurl
./ros setup --no-core;./ros ../scripts/man.ros ../documents/ros.html ../documents/ros.1
ros(48004,0x7fff7385d300) malloc: *** error for object 0x7fff592d85d9: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
/bin/sh: line 1: 48004 Abort trap: 6           ./ros setup --no-core
ros(48006,0x7fff7385d300) malloc: *** error for object 0x7fff501025dd: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
/bin/sh: line 1: 48006 Abort trap: 6           ./ros ../scripts/man.ros ../documents/ros.html ../documents/ros.1
make[1]: *** [../documents/ros.1] Error 134
make: *** [install-recursive] Error 1
Warning: It appears you have MacPorts or Fink installed.
Software installed with other package managers causes known problems for
Homebrew. If a formula fails to build, uninstall MacPorts/Fink and try again.

so I try install roswell from source code. 
>
$ git clone -b release https://github.com/snmsts/roswell.git
$ cd roswell
$ sh bootstrap
$ ./configure
$ make
$ sudo make install

sudo make install result is:
>
Making install in src
printf "#define ROS_COMPILE_ENVIRONMENT \"%s\"\n" "`gcc --version|head -n 1`" > gend.h.tmp
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
(printf "#define ROS_REVISION \"" && ((which git>/dev/null&&[ -e ../.git ]&& \
        (git log -n 1 --oneline|cut -d' ' -f1| tr -d '\n'| tr -d '\r'))||printf "") && printf "\"\n") >> gend.h.tmp
(sh -c 'cd /usr/local/share/common-lisp/source/roswell; pwd -W' 2>&1 >/dev/null && (printf "#define WIN_LISP_PATH \"" \
        echo `sh -c 'cd /usr/local/share/common-lisp/source/roswell; pwd -W 2>/dev/null'`| tr -d '\n'| tr -d '\r' |\
        sed /\//\\/ \
        printf "\\\\\"\n")  >> gend.h.tmp) || printf ""
sh: line 0: pwd: -W: invalid option
pwd: usage: pwd [-LP]
cmp -s gend.h.tmp gend.h||cp gend.h.tmp gend.h
rm -f gend.h.tmp
cat gend.h
#define ROS_COMPILE_ENVIRONMENT "Apple LLVM version 6.1.0 (clang-602.0.49) (based on LLVM 3.6.0svn)"
#define ROS_REVISION "b3293ce"
printf "#define ROS_COMPILE_ENVIRONMENT \"%s\"\n" "`gcc --version|head -n 1`" > gend.h.tmp
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
(printf "#define ROS_REVISION \"" && ((which git>/dev/null&&[ -e ../.git ]&& \
        (git log -n 1 --oneline|cut -d' ' -f1| tr -d '\n'| tr -d '\r'))||printf "") && printf "\"\n") >> gend.h.tmp
(sh -c 'cd /usr/local/share/common-lisp/source/roswell; pwd -W' 2>&1 >/dev/null && (printf "#define WIN_LISP_PATH \"" \
        echo `sh -c 'cd /usr/local/share/common-lisp/source/roswell; pwd -W 2>/dev/null'`| tr -d '\n'| tr -d '\r' |\
        sed /\//\\/ \
        printf "\\\\\"\n")  >> gend.h.tmp) || printf ""
sh: line 0: pwd: -W: invalid option
pwd: usage: pwd [-LP]
cmp -s gend.h.tmp gend.h||cp gend.h.tmp gend.h
rm -f gend.h.tmp
cat gend.h
#define ROS_COMPILE_ENVIRONMENT "Apple LLVM version 6.1.0 (clang-602.0.49) (based on LLVM 3.6.0svn)"
#define ROS_REVISION "b3293ce"
 .././install-sh -c -d '/usr/local/bin'
  /usr/bin/install -c ros '/usr/local/bin'
 .././install-sh -c -d '/usr/local/share/common-lisp/source/roswell'
 /usr/bin/install -c -m 644 lisp/init.lisp lisp/install+7zip.lisp lisp/install+asdf3.lisp lisp/install+ffcall.lisp lisp/install+msys2.lisp lisp/install+quicklisp.lisp lisp/install+sigsegv.lisp lisp/install-ccl-bin.lisp lisp/install-clisp.lisp lisp/install-sbcl-bin.lisp lisp/install-sbcl.lisp lisp/install.lisp lisp/+roswell-internal-core-build.ros lisp/build.ros lisp/delete.ros lisp/dump.ros lisp/emacs.ros lisp/init.ros lisp/list.ros lisp/use.ros '/usr/local/share/common-lisp/source/roswell'
make[2]: Nothing to be done for `install-exec-am'.
make[2]: Nothing to be done for `install-data-am'.

I get below issue message when use ros:
>
➜  roswell git:(master) ✗ ros
ros(49935,0x7fff7385d300) malloc: *** error for object 0x7fff52f11cfe: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
[1]    49935 abort      ros

I can get the same issue message when run
>
ros config

**Comment by snmsts** [comment]
Thank you for the information.
Now I understand that roswell not working at all there.
I'm not sure what's wrong so far and It's sounds not so easy bug to fix at once. I'll try fixing it but I can't tell when I'll finish.
Would you show ``uname -a``? that might helpful.

**Comment by Habens** [comment]
>
$ uname -a
Darwin CNwjchen.local 14.5.0 Darwin Kernel Version 14.5.0: Wed Jul 29 02:26:53 PDT 2015; root:xnu-2782.40.9~1/RELEASE_X86_64 x86_64

**Comment by snmsts** [comment]
thank you.

**Comment by Habens** [comment]
Ohh, It looks like this issue from incorrect permissions on ros. Roswell can works well when I use below command
>
✗ sudo ros --version
Password:
roswell 0.0.3.49(7ab732a)
