### ISSUE TITLE
"help" command implementation should be separated

### ISSUE THREAD

**Issue by guicho271828** [snmsts/roswell#82]
As in https://github.com/git/git/blob/master/builtin/help.c and in CIM.
In git, help commands are just an alias to the man pages, e.g. `git help init` invokes `man git-init`.

The point is, this is a good design in terms of maintainance of the documentation.
A writer of man page does not have to care about the internals of roswell.

**Comment by guicho271828** [comment]
well I might work on it

**Comment by snmsts** [comment]
I agree.
My question for this issue is what is acceptable documentation system for windows without unix compatible subsystem?

**Comment by guicho271828** [comment]
if there are `less` counterpart on windows, then just dumping the text to a static file and showing the results would be enough.

**Comment by guicho271828** [comment]
and this is CIM's approach.

**Comment by guicho271828** [comment]
groff? http://stackoverflow.com/questions/944434/where-is-the-man-program-for-windows-program-to-open-unix-man-pages

**Comment by snmsts** [comment]
Sorry to bother you.Just think about unix.I'll find a way...

**Comment by snmsts** [comment]
separation itself has done. Remaining issue is decide what tool to use for docs.
