### ISSUE TITLE
Options Intercepted by SBCL in Built Executables

### ISSUE THREAD

**Issue by noctuid** [snmsts/roswell#88]
For example, `./my_script.ros --help` will correctly display my_script's help message, but after using roswell's build command to generate an executable, `./my_script --help` will print sbcl's help message. I'm guessing this is because roswell gets passed the options first in the first case, but roswell isn't involved in the second case. I know this can be prevented when running scripts with sbcl using `--script` (for `--end-toplevel-options`), but is there some way to have `ros build` prevent this from happening for a compiled executable?

**Comment by snmsts** [comment]
Thank you very much for the report.
I confirmed the problem and short answer for your question is No for current version.
For the purpose of the `ros build` I think the default behavior should be changed. 

I will release fixed version https://github.com/snmsts/roswell/commit/a4cc9ec21eb92f3eab94227a7ca02800d55cb8db this weekend.

**Comment by noctuid** [comment]
Awesome, thank you for the quick fix!

**Comment by snmsts** [comment]
done.
