### ISSUE TITLE
Boot a copy of the running implementation from itself?

### ISSUE THREAD

**Issue by eudoxia0** [snmsts/roswell#91]
I'm building this library that needs to start a new process of the implementation it's running on -- the executable, the core, any init code, that kind of stuff.

I haven't really figured out how to do this with Roswell. When trying to boot SBCL with the included core, I get a bunch of contrib-loading errors, presumably because the `SBCL_HOME` variable is not set properly, and even then I can't actually load the Quicklisp setup file because it fails.

Do you have any tips for this? I've looked at `cmd-run-sbcl.c` but can't successfully run what the comment claims it does. That is, the following:

```bash
$> ./.roswell/impls/x86-64/linux/sbcl-bin/1.2.14/bin/sbcl --core ~/.roswell/impls/x86-64/linux/sbcl-bin/1.2.14/lib/sbcl/sbcl.core --load /usr/local/share/common-lisp/source/roswell/init.lisp --eval '(print 1)'
```

Returns immediately and prints nothing.

**Comment by snmsts** [comment]
If you installed roswell,why don't you use roswell?

```
 ros -m sbcl -e '(print 1)'
```

or from lisp

```
#+ros.init
(ros:roswell `("-L"
               ,(ros:roswell '("config" "show" "default.lisp") :string t)
               "-m" "sbcl"
               "-e" "\"(print 1)\"")
             :interactive)

```

**Comment by eudoxia0** [comment]
I guess I was looking for a more 'generic' version. Then again, I could check whether the pathname contains ".roswell" and use that I guess. Thanks!
